src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="`user`")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }
}

templates/erp/base.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>ERP Vortex</title>

    <script src="https://kit.fontawesome.com/c46f4b8baa.js" crossorigin="anonymous"></script>


    <!-- Bootstrap -->
    <link href="{{ asset('vendors/bootstrap/dist/css/bootstrap.min.css') }}" rel="stylesheet">
    <!-- Font Awesome -->
    {#<link href="{{ asset('vendors/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet">#}
    <!-- NProgress -->
    <link href="{{ asset('vendors/nprogress/nprogress.css') }}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{{ asset('build/css/custom.css') }}" rel="stylesheet">
</head>

<body class="nav-md">
<div class="container body">
    <div class="main_container">
        <div class="col-md-3 left_col footer_fixed">
            <div class="left_col scroll-view">
                <div class="navbar nav_title" style="border: 0;">
                    <a href="index.html" class="site_title"><i class="fa fa-sellsy"></i> <span>Vortex ERP</span></a>
                </div>

                <div class="clearfix"></div>

                <!-- menu profile quick info -->
                {#{{  include('erp/menu_profile.html.twig')  }}#}
                <!-- /menu profile quick info -->

                <br/>

                <!-- sidebar menu -->
                {{   include('erp/sidebar.html.twig') }}
                <!-- /sidebar menu -->

                <!-- /menu footer buttons -->
                {{ include('erp/menu_footer.html.twig') }}
                <!-- /menu footer buttons -->
            </div>
        </div>

        <!-- top navigation -->
        {{ include('erp/top_navigation.html.twig') }}
        <!-- /top navigation -->

        <!-- page content -->
        {#{{ include('erp/page_content.html.twig') }}#}
        {% block page_content %}

        {% endblock %}
        <!-- /page content -->



        <!-- footer content -->
        {{ include('erp/footer_content.html.twig') }}
        <!-- /footer content -->
    </div>
</div>


<!-- jQuery -->
<script src="{{ asset('vendors/jquery/dist/jquery.min.js') }}"></script>
<!-- Bootstrap -->
<script src="{{ asset('vendors/bootstrap/dist/js/bootstrap.bundle.min.js') }}"></script>
<!-- FastClick -->
<script src="{{ asset('vendors/fastclick/lib/fastclick.js') }}"></script>
<!-- NProgress -->
<script src="{{ asset('vendors/nprogress/nprogress.js') }}"></script>

<!-- Custom Theme Scripts -->
<script src="{{ asset('build/js/custom.min.js') }}"></script>

{% block javascript %}
{% endblock %}
</body>
</html>

templates/erp/dashboard.html.twig
{% extends 'erp/base.html.twig' %}
{% block page_content %}
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Plain Page</h3>
            </div>

            <div class="title_right">
                <div class="col-md-5 col-sm-5   form-group pull-right top_search">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search for...">
                        <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                    </span>
                    </div>
                </div>
            </div>
        </div>

        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-12 col-sm-12  ">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Plain Page</h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" href="#">Settings 1</a>
                                    <a class="dropdown-item" href="#">Settings 2</a>
                                </div>
                            </li>
                            <li><a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/erp/footer_content.html.twig
<footer>
    <div class="pull-right">
        Vortex ERP
    </div>
    <div class="clearfix"></div>
</footer>

templates/erp/menu_footer.html.twig
<div class="sidebar-footer hidden-small">
    <a data-toggle="tooltip" data-placement="top" title="Settings">
        <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="FullScreen">
        <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="Lock">
        <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
    </a>
</div>

templates/erp/menu_profile.html.twig
<div class="profile clearfix">
    <div class="profile_pic">
        <img src="{{ asset('images/img.jpg') }}" alt="..." class="img-circle profile_img">
    </div>
    <div class="profile_info">
        <span>Welcome,</span>
        <h2>John Doe</h2>
    </div>
    <div class="clearfix"></div>
</div>

templates/erp/sidebar.html.twig
<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
    <div class="menu_section">
        {#<h3>General</h3>#}
        <ul class="nav side-menu">
            <li><a><i class="fa fa-cash-register"></i> Vendas <span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                    <li><a href="index.html">PDV</a></li>
                    <li><a href="index2.html">Pedidos de Venda</a></li>
                    <li><a href="index3.html">Nota Fiscal</a></li>
                    <li><a href="index3.html">Nota Fiscal Consumidor</a></li>
                    <li><a href="index3.html">Pedido de Venda</a></li>
                </ul>
            </li>
            <li><a><i class="fa fa-shopping-basket"></i> Compras <span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                    <li><a href="form.html">Entrada de Nota</a></li>
                    <li><a href="form_advanced.html">Pedido de Compra</a></li>
                </ul>
            </li>
            <li><a><i class="fa fa-boxes"></i> Estoques <span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                    <li><a href="general_elements.html">Movimentações</a></li>
                    <li><a href="media_gallery.html">Inventário</a></li>
                </ul>
            </li>
            <li><a><i class="fa fa-percentage"></i>Financeiro <span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                    <li><a href="fixed_sidebar.html">Fluxo de Caixa</a></li>
                    <li><a href="fixed_footer.html">Remessa/Retorno</a></li>
                </ul>
            </li>
            <li><a><i class="fa fa-minus-square"></i>Contas a Pagar <span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                    <li><a href="fixed_sidebar.html">Lançamentos</a></li>
                    <li><a href="fixed_footer.html">Agenda</a></li>
                </ul>
            </li>
            <li><a><i class="fa fa-plus-square"></i>Contas a Receber <span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                    <li><a href="fixed_sidebar.html">Fixed Sidebar</a></li>
                    <li><a href="fixed_footer.html">Fixed Footer</a></li>
                </ul>
            </li>
            <li><a><i class="fa fa-table"></i> Cadastros <span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                    <li><a href="tables.html">Produtos</a></li>
                    <li><a href="tables_dynamic.html">Clientes/Fornecedores</a></li>
                    <li><a href="tables_dynamic.html">Usuários</a></li>
                    <li><a href="tables_dynamic.html">Configurações</a></li>
                    <li><a href="tables_dynamic.html">Empresa</a></li>
                </ul>
            </li>
            <li><a><i class="fa fa-chart-bar"></i> Relatórios <span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                    <li><a href="tables.html">Produtos</a></li>
                    <li><a href="tables_dynamic.html">Clientes/Fornecedores</a></li>
                    <li><a href="tables_dynamic.html">Usuários</a></li>
                    <li><a href="tables_dynamic.html">Configurações</a></li>
                    <li><a href="tables_dynamic.html">Empresa</a></li>
                </ul>
            </li>
            <li><a><i class="fa fa-envelope"></i> Email Mkt <span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                    <li><a href="{{ path('listas_email_marketing') }}">Listas</a></li>
                    <li><a href="chartjs2.html">Campanhas</a></li>
                    <li><a href="morisjs.html">Relatórios</a></li>
                </ul>
            </li>

        </ul>
    </div>


</div>

templates/erp/top_navigation.html.twig
<div class="top_nav">
    <div class="nav_menu">
        <div class="nav toggle">
            <a id="menu_toggle"><i class="fa fa-bars"></i></a>
        </div>
        <nav class="nav navbar-nav">
            <ul class=" navbar-right">
                <li class="nav-item dropdown open" style="padding-left: 15px;">
                    <a href="javascript:;" class="user-profile dropdown-toggle" aria-haspopup="true" id="navbarDropdown"
                       data-toggle="dropdown" aria-expanded="false">
                        <i class="fas  fa-user"></i>
                        {% if is_granted("ROLE_USER") %}
                            {{ app.user.username }}
                        {% endif %}
                    </a>
                    <div class="dropdown-menu dropdown-usermenu pull-right" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="javascript:;"><i class="fa fa-user-cog"></i>  Meus dados</a>
                        <a class="dropdown-item" href="javascript:;"><i class="fa fa-question"></i> Ajuda</a>
                        <a class="dropdown-item" href="login.html"><i class="fa fa-sign-out pull-right"></i> Log Out</a>
                    </div>
                </li>

                <li role="presentation" class="nav-item dropdown open">
                    <a href="javascript:;" class="dropdown-toggle info-number" id="navbarDropdown1"
                       data-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-envelope-o"></i>
                        <span class="badge bg-green">6</span>
                    </a>
                    <ul class="dropdown-menu list-unstyled msg_list" role="menu" aria-labelledby="navbarDropdown1">
                        <li class="nav-item">
                            <a class="dropdown-item">
                                <span class="image"><img src="{{ asset('images/img.jpg') }}"
                                                         alt="Profile Image"/></span>
                                <span>
                            <span>John Smith</span>
                            <span class="time">3 mins ago</span>
                          </span>
                                <span class="message">
                            Film festivals used to be do-or-die moments for movie makers. They were where...
                          </span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="dropdown-item">
                                <span class="image"><img src="{{ asset('images/img.jpg') }}"
                                                         alt="Profile Image"/></span>
                                <span>
                            <span>John Smith</span>
                            <span class="time">3 mins ago</span>
                          </span>
                                <span class="message">
                            Film festivals used to be do-or-die moments for movie makers. They were where...
                          </span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="dropdown-item">
                                <span class="image"><img src="{{ asset('images/img.jpg') }}"
                                                         alt="Profile Image"/></span>
                                <span>
                            <span>John Smith</span>
                            <span class="time">3 mins ago</span>
                          </span>
                                <span class="message">
                            Film festivals used to be do-or-die moments for movie makers. They were where...
                          </span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="dropdown-item">
                                <span class="image"><img src="{{ asset('images/img.jpg') }}"
                                                         alt="Profile Image"/></span>
                                <span>
                            <span>John Smith</span>
                            <span class="time">3 mins ago</span>
                          </span>
                                <span class="message">
                            Film festivals used to be do-or-die moments for movie makers. They were where...
                          </span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <div class="text-center">
                                <a class="dropdown-item">
                                    <strong>See All Alerts</strong>
                                    <i class="fa fa-angle-right"></i>
                                </a>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
    </div>
</div>